### ISSUE TITLE
[UITableViewCell setLoading:] Unrecognized selector sent to instance

### ISSUE THREAD

**Issue by eshwartm** [OliverLetterer/SLExpandableTableView#31]
I have a done a basic setup of a table view of type SLExpandableTableView. What am I missing in my setup?

I implemented 

    - (UITableViewCell<UIExpandingTableViewCell> *)tableView:(SLExpandableTableView *)tableView expandingCellForSection:(NSInteger)section

This method is where the cell goes to perform `setLoading` and then it crashes with unrecognized selector error.

I made a custom UITableViewCell subscribing to `UIExpandingTableViewCell` protocol to try and allay the problem. But that still doesn't work.

**Comment by OliverLetterer** [comment]
Sample code is available [here](https://github.com/OliverLetterer/SLExpandableTableView/blob/master/Tests/SLExpandableTableViewTests/SLExpandableTableViewController.m), which might help solve your problem.

**Comment by jayesh15111988** [comment]
@eshwartm Were you able to figure out what the problem was causing this crash?

**Comment by niftykurian** [comment]
hey i have the same issue. could some one help me with it? thanks in advance :)
