### ISSUE TITLE
Cannot conform to the cell protocol with Swift

### ISSUE THREAD

**Issue by Anders123fr** [OliverLetterer/SLExpandableTableView#38]
Hey,

Thank you for an awesome framework!

I am trying to conform to the ```UIExpandingTableViewCell``` with Swift, but I'm unable to do so.
I have tried to do it in many ways with initializers etc, as explained here also: 
http://stackoverflow.com/questions/27932235/conforming-to-an-obj-c-protocols-property-in-swift

Is it not possible to use the framework in Swift or am I doing it wrong?

Here is the table view cell subclass that I am trying with:

```
import UIKit
import SLExpandableTableView

class PresentationListItemTVC : UITableViewCell, UIExpandingTableViewCell {	
	var loading: Bool = false

	var expansionStyle: UIExpansionStyle = UIExpansionStyleExpanded

	func setExpansionStyle(style: UIExpansionStyle, animated: Bool) {		
	}	
}

**Comment by Anders123fr** [comment]
![skaermbillede 2015-09-10 14 04 55](https://cloud.githubusercontent.com/assets/1019341/9787663/effa86a4-57c4-11e5-935f-6407e865439c.png)

Here are the issues

**Comment by kingiol** [comment]
Wish cloud help you .

http://stackoverflow.com/questions/32254051/how-to-conform-to-objective-c-protocol-with-readonly-properties-in-swift

**Comment by Anders123fr** [comment]
It worked - thank you!

**Comment by sharsad** [comment]
can u send swift complete code ?
