### ISSUE TITLE
Unable to install through pods

### ISSUE THREAD

**Issue by RajChanchal** [OliverLetterer/SLExpandableTableView#40]
I tried: pod 'SLExpandableTableView'

[!] Error installing SLExpandableTableView
[!] /usr/local/bin/git clone https://github.com/OliverLetterer/SLExpandableTableView.git /var/folders/y7/9q2l4lcs1hx1mg145hm1td6w0000gn/T/d20151207-61737-69xdbj --single-branch --depth 1 --branch 1.3.1

Cloning into '/var/folders/y7/9q2l4lcs1hx1mg145hm1td6w0000gn/T/d20151207-61737-69xdbj'...
fatal: unable to access 'https://github.com/OliverLetterer/SLExpandableTableView.git/': Could not resolve host: github.com

**Comment by OliverLetterer** [comment]
`Could not resolve host: github.com` is not a problem with SLExpandableTableView.
