### ISSUE TITLE
Background colors of cells are changing while expanding/collapsing

### ISSUE THREAD

**Issue by D34thStalker** [OliverLetterer/SLExpandableTableView#42]
I am having an issue where there background color of the cells are changing while the cells expand/collapse.
I am creating a rounded view by manipulating the layer and i change the layer background color to white so only the rounded area stays white while i set the actual view background color to clear.
Using this, it seems like the layer's white color is being removed when the cells are expanding or collapsing. How can I fix this so the animation includes the cells set colors?

**Comment by OliverLetterer** [comment]
SLExpandableTableView does not manage the state of the cell's background color. So this is not an issue with SLExpandableTableView.
